# Generated by Django 4.2.30 on 2026-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('categorie', models.CharField(blank=True, choices=[('Roman', 'Roman'), ('Science', 'Science'), ('Histoire', 'Histoire'), ('Informatique', 'Informatique'), ('Philosophie', 'Philosophie'), ('Poésie', 'Poésie'), ('Biographie', 'Biographie'), ('Autre', 'Autre')], max_length=100)),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunté', 'Emprunté'), ('réservé', 'Réservé')], default='disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['titre'],
            },
        ),
    ]
